Repository MoViDe-Project/motis, pull requests merged in 2025-03, with the labels that each got.

#58 chore: update PR template
  .github/pull_request_template.md
Labels: chore

#60 feat: leg attribute comparison
  visual-debugger/assets/Query-Batch.json
  visual-debugger/src/data-processing/changeElements.ts
  visual-debugger/src/data-processing/compareObjects.ts
  visual-debugger/src/data-processing/comparePlans.ts
  visual-debugger/src/data-processing/componentInterface.ts
  visual-debugger/src/data-processing/type-declarations/comparisonShadows.ts
  visual-debugger/src/lib/components/ui/ConnectionDetail.svelte
  visual-debugger/src/lib/components/ui/DefaultItineraryOverview.svelte
  visual-debugger/src/lib/components/ui/DefaultPlanOverview.svelte
  visual-debugger/src/lib/components/ui/ItineraryOverview.svelte
  visual-debugger/src/lib/components/ui/PlanOverview.svelte
  visual-debugger/src/lib/components/ui/QueryBatchOverview.svelte
  visual-debugger/src/lib/components/ui/Route.svelte
  visual-debugger/src/lib/components/ui/button/index.ts
  visual-debugger/src/lib/components/ui/subcomponents/LegEntry.svelte
  visual-debugger/src/lib/components/ui/subcomponents/MatchIndicator.svelte
  visual-debugger/src/lib/components/ui/subcomponents/PlanEntry.svelte
  visual-debugger/src/lib/components/ui/subcomponents/QueryEntry.svelte
  visual-debugger/src/lib/formatDuration.ts
  visual-debugger/src/lib/toDateTime.ts
  visual-debugger/src/sveltestore.ts
Labels: enhancement, user story, Front End, Data Processing

#56 feat: Include unit tests for data processing
  visual-debugger/src/data-processing/changeElements.ts
  visual-debugger/src/data-processing/comparePlans.ts
  visual-debugger/src/data-processing/planParsing.ts
  visual-debugger/src/data-processing/tests/changeElements.test.ts
  visual-debugger/src/data-processing/tests/comparePlans.test.ts
  visual-debugger/src/data-processing/tests/planParsing.test.ts
  visual-debugger/src/data-processing/tests/queryBuild.test.ts
Labels: Data Processing

#67 fix: fix highlighting of missing itineraries
  visual-debugger/src/data-processing/comparePlans.ts
  visual-debugger/src/data-processing/styling/cssClasses.ts
Labels: bug

#70 fix: unequal number of attributes
  visual-debugger/assets/Query-Batch.json
  visual-debugger/assets/default-plan-mismatched.json
  visual-debugger/src/data-processing/compareObjects.ts
  visual-debugger/src/data-processing/comparePlans.ts
  visual-debugger/src/lib/components/ui/ConnectionDetail.svelte
Labels: bug, Data Processing

#72 fix: hotfix for highlighting default plan entries as missing
  visual-debugger/src/data-processing/comparePlans.ts
Labels: bug, Data Processing

#71 Feat: plan overview icons
  visual-debugger/src/data-processing/comparePlans.ts
  visual-debugger/src/data-processing/type-declarations/comparisonShadows.ts
  visual-debugger/src/lib/components/ui/subcomponents/PlanEntry.svelte
  visual-debugger/src/routes/+page.svelte
Labels: enhancement, Data Processing

#73 feat: plan filters
  visual-debugger/src/data-processing/changeElements.ts
  visual-debugger/src/data-processing/componentInterface.ts
  visual-debugger/src/data-processing/filterItineraries.ts
  visual-debugger/src/data-processing/tests/changeElements.test.ts
  visual-debugger/src/lib/components/ui/checkbox/checkbox.svelte
  visual-debugger/src/lib/components/ui/checkbox/index.ts
  visual-debugger/src/lib/components/ui/subcomponents/QueryEntry.svelte
  visual-debugger/src/routes/+page.svelte
  visual-debugger/src/sveltestore.ts
Labels: enhancement, Front End

#78 feat: correct behavior on screen size change
  visual-debugger/src/lib/components/ui/subcomponents/MatchIndicator.svelte
  visual-debugger/src/lib/components/ui/subcomponents/PlanEntry.svelte
  visual-debugger/src/routes/+page.svelte
Labels: enhancement, Front End

#77 Feat: api geocodes
  visual-debugger/assets/query-batch-geo.json
  visual-debugger/src/data-processing/componentInterface.ts
  visual-debugger/src/data-processing/planParsing.ts
  visual-debugger/src/data-processing/queryBuild.ts
  visual-debugger/src/data-processing/tests/queryBuild.test.ts
  visual-debugger/src/data-processing/type-declarations/queryTypes.ts
  visual-debugger/src/lib/components/ui/QueryBatchOverview.svelte
  visual-debugger/src/lib/components/ui/subcomponents/QueryEntry.svelte
  visual-debugger/src/lib/components/ui/upload/QueryUpload.svelte
  visual-debugger/src/sveltestore.ts
Labels: enhancement, Data Processing

#85 chore: added how to use file
  visual-debugger/HowToUse.md
  visual-debugger/README.md
Labels: documentation, chore

#86 fix: Improve error handling
  visual-debugger/assets/Query-Batch.json
  visual-debugger/assets/query-batch.json
  visual-debugger/src/data-processing/changeElements.ts
  visual-debugger/src/data-processing/planParsing.ts
  visual-debugger/src/data-processing/tests/changeElements.test.ts
  visual-debugger/src/data-processing/tests/comparePlans.test.ts
  visual-debugger/src/data-processing/tests/planParsing.test.ts
  visual-debugger/src/data-processing/tests/queryBuild.test.ts
Labels: bug

#89 chore: label changes
  visual-debugger/HowToUse.md
  visual-debugger/src/lib/components/ui/upload/DefaultPlanUpload.svelte
  visual-debugger/src/lib/components/ui/upload/QueryUpload.svelte
  visual-debugger/src/routes/+page.svelte
  visual-debugger/src/routes/itinerary-comp/+page.svelte
Labels: chore, Front End
